AllCops:
  Exclude:
    - '*.gemspec'

Bundler/DuplicatedGem:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/IndentHeredoc:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/RescueWithoutErrorClass:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Security/Eval:
  Exclude:
    - 'features/**/*_steps.rb'

Style/BracesAroundHashParameters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  MaxLineLength: 40

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SignalException:
  EnforcedStyle: semantic

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
