sudo: false
language: ruby
rvm:
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.10'
  - '2.3.8'
  - '2.4.5'
  - '2.5.3'
before_install:
  - gem install bundler
  - ruby -e 'require "rubygems"; require "bundler/inline"; gemfile{ source "https://rubygems.org"; gem "rubygems-update" }' # get compatible version of rubygems-update
  - gem update --system
script: bundle exec cucumber --expand
matrix:
  include:
    - os: osx
      rvm: default
    - env: RUBOCOP=✓
      rvm: '2.5.3'
      script: bundle exec rubocop
    - env: CHECK_RUBIES=✓
      rvm: '2.5.3'
      script: bundle exec travis_check_rubies
