sudo: false
language: ruby
rvm:
  - '1.8'
  - '1.9'
  - '2.0'
  - '2.1'
  - '2.2'
script:
  if [ -n "$RUBOCOP" ]; then
    bundle exec rubocop
  ; else
    bundle exec cucumber
  ; fi
matrix:
  fast_finish: true
  include:
    - env: RUBOCOP=true
      rvm: '2'
