language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - '2.0'
  - '2.1'
script:
  if [ -n "$RUBOCOP" ]; then
    bundle exec rubocop
  ; else
    bundle exec cucumber
  ; fi
matrix:
  fast_finish: true
  include:
    - env: RUBOCOP=true
      rvm: default
