sudo: false
language: ruby
rvm:
  - '1.8.7-p371'
  - '1.9.3-p551'
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.6'
  - '2.3.3'
  - '2.4.0'
script: bundle exec cucumber
matrix:
  include:
    - env: RUBOCOP=✓
      rvm: '2.4.0'
      script: bundle exec rubocop
    - env: CHECK_RUBIES=✓
      rvm: '2.4.0'
      script: bundle exec travis_check_rubies
