sudo: false
language: ruby
rvm:
  - '1.8.7-p371'
  - '1.9.3-p551'
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.9'
  - '2.3.6'
  - '2.4.3'
  - '2.5.0'
before_install:
  - gem update --system
  - gem update bundler
script: bundle exec cucumber --expand
matrix:
  include:
    - os: osx
      rvm: default
    - env: RUBOCOP=✓
      rvm: '2.4.3'
      script: bundle exec rubocop
    - env: CHECK_RUBIES=✓
      rvm: '2.4.3'
      script: bundle exec travis_check_rubies
