sudo: false
language: ruby
rvm:
  - '2.0.0-p648'
  - '2.1.10'
  - '2.2.10'
  - '2.3.8'
  - '2.4.5'
  - '2.5.3'
  - '2.6.0'
before_install:
  - gem install rubygems-update || gem install rubygems-update --version '< 3'
  - gem update --system
  - gem install bundler || gem install bundler --version '< 2'
script: bundle exec cucumber --expand
matrix:
  include:
    - os: osx
      rvm: default
    - env: RUBOCOP=✓
      rvm: '2.5.3'
      script: bundle exec rubocop
    - env: CHECK_RUBIES=✓
      rvm: '2.5.3'
      script: bundle exec travis_check_rubies
